// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPSPEa5-Q-wgaz3s38EZXOmhCFT7xdehw',
    appId: '1:903782548174:ios:6f6f938fd0d06c74f7c69f',
    messagingSenderId: '903782548174',
    projectId: 'myprojectfirebase-ed480',
    storageBucket: 'myprojectfirebase-ed480.firebasestorage.app',
    iosClientId: '903782548174-c0n0gai0nd4ld4mra4hugijsf23ba6bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uts1123150125Bagstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPSPEa5-Q-wgaz3s38EZXOmhCFT7xdehw',
    appId: '1:903782548174:ios:6f6f938fd0d06c74f7c69f',
    messagingSenderId: '903782548174',
    projectId: 'myprojectfirebase-ed480',
    storageBucket: 'myprojectfirebase-ed480.firebasestorage.app',
    iosClientId: '903782548174-c0n0gai0nd4ld4mra4hugijsf23ba6bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.uts1123150125Bagstore',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcG9TxybmWevmSX2_VY5KbnXsbxt_Td3w',
    appId: '1:903782548174:web:7bc6631ab13db004f7c69f',
    messagingSenderId: '903782548174',
    projectId: 'myprojectfirebase-ed480',
    authDomain: 'myprojectfirebase-ed480.firebaseapp.com',
    storageBucket: 'myprojectfirebase-ed480.firebasestorage.app',
    measurementId: 'G-HRNZ292GPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARHsxKIBb0e8SUa0s9kcc3BQ_R8l5_WAQ',
    appId: '1:903782548174:android:181ef91e770a7df5f7c69f',
    messagingSenderId: '903782548174',
    projectId: 'myprojectfirebase-ed480',
    storageBucket: 'myprojectfirebase-ed480.firebasestorage.app',
  );

}